#! /bin/sh

# make copy of local samba config. we'll be copying a new config onto the container.
cp /etc/samba/smb.conf /etc/samba/smb.conf.bak
# we'll be modifying fstab, so back it up
cp /etc/fstab /etc/fstab.bak

# add share to definitions in smb.conf file:
echo '\n[backups]\n\tcomment = Backups\n\tpath = /mnt/backups/backups\n\tvalid users = keeper\n\tread only = no\n\tvfs objects = catia fruit streams_xattr\n\tfruit:time machine = yes' | sudo tee -a /etc/samba/smb.conf

# if /mnt/backups does not yet exist, create it, register it in fstab, and mount it
if [ ! -d /mnt/backups ] ; then
    mkdir /mnt/backups
    echo 'LABEL=backups /mnt/backups ext4 noexec,nodev,noatime,nodiratime 0 0' | sudo tee -a /etc/fstab
    mount /mnt/backups
fi

